version: "3"

vars:
  # All available variants
  VARIANTS: architecture idp mcp gitops jit kitchen-sink security poc-eval billing

  # Default variants for build:datasheet (matches original npm script)
  DEFAULT_VARIANTS: idp mcp gitops jit

  # Directories
  DIST_DIR: ./dist
  PDF_OUTPUT_DIR: ../../../static/pdfs

  # Source patterns for watching and dependency tracking
  SRC_PATTERN: src/**/*.{tsx,ts,jsx,js,css,mdx}
  ASSETS_PATTERN: assets/**/*
  STYLES_FILE: styles.css

tasks:
  # ============================================================================
  # Base Tasks (Parameterized)
  # ============================================================================

  clean:
    desc: "Clean build outputs"
    cmds:
      - rm -rf {{.DIST_DIR}}
      - mkdir -p {{.DIST_DIR}}

  build:
    sources:
      - src/**/*.{tsx,ts,jsx,js,css,mdx}
      - cli/src/**/*.{tsx,ts,jsx,js,css,mdx}
    cmds:
      - npm run build

  install:
    deps:
      - build
    cmds:
      - cp dist/facet /usr/local/bin

  storybook:
    desc: "Run Storybook development server on port 6006"
    cmds:
      - npm run storybook

  storybook:build:
    desc: "Build static Storybook for deployment"
    cmds:
      - npm run build-storybook

  test:storybook:
    desc: "Build Storybook and verify all stories load without errors"
    cmds:
      - npm run build-storybook
      - echo "✓ Storybook build completed successfully"
      - echo "✓ All stories compiled without errors"

  tarball:
    desc: "Create platform-specific tarball for Go embedding"
    cmds:
      - cd cli && npm install
      - tar czf cmd/facet/facet-cli.tar.gz
          --exclude='cli/dist' --exclude='cli/test' --exclude='cli/.git'
          cli/src cli/vite-ssr-loader.ts cli/package.json cli/node_modules
          package.json src/styles.css

  build:go:
    desc: "Build Go launcher binary"
    deps: [tarball]
    cmds:
      - go build -ldflags "-X main.version={{.CLI_VERSION}} -X main.commit={{.GIT_COMMIT}}"
          -o dist/facet ./cmd/facet
    vars:
      CLI_VERSION:
        sh: node -p "require('./cli/package.json').version"
      GIT_COMMIT:
        sh: git rev-parse --short HEAD

  test:e2e:
    desc: "Run Go launcher e2e tests"
    deps: [tarball]
    cmds:
      - cd e2e && go test -v ./... -count=1 -timeout 5m

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
