#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const pkg = require('../package.json');

let sha = process.env.GIT_COMMIT || 'unknown';
let dirty = false;
try {
  const opts = { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] };
  sha = execSync('git rev-parse --short HEAD', opts).trim();
  dirty = execSync('git status --porcelain', opts).trim().length > 0;
} catch {}

const commit = sha + (dirty ? '-dirty' : '');
const buildDate = new Date().toISOString().replace('T', ' ').slice(0, 16);

const out = `// DO NOT MODIFY — this file is auto-generated by scripts/gen-version.cjs
export const VERSION=${JSON.stringify(pkg.version)};
export const BUILD_DATE=${JSON.stringify(buildDate)};
export const GIT_COMMIT=${JSON.stringify(commit)};
`;

const target = path.join(__dirname, '..', 'src', 'version-generated.ts');
fs.writeFileSync(target, out);
