#!/usr/bin/env node
// Inlines the Fill-PDF playground sample assets (blank PDF + x-pdf schema +
// example data) into cli/src/server/samples/generated.ts. PDFs are base64
// (binary), schema/data are kept as JSON text. Inlining (vs `with { type:
// 'file' }`) is the one encoding that loads identically under tsdown (the npm
// lib build, which can't read binary file-imports), the bun-compiled binary,
// and bun test.
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'src', 'server', 'samples');
const ids = ['f1120', 'f5471'];

const entries = ids.map((id) => {
  const pdfB64 = fs.readFileSync(path.join(dir, `${id}.pdf`)).toString('base64');
  const schema = fs.readFileSync(path.join(dir, `${id}.schema.json`), 'utf-8');
  const data = fs.readFileSync(path.join(dir, `${id}.data.json`), 'utf-8');
  return `  ${JSON.stringify(id)}: {\n    pdfB64: ${JSON.stringify(pdfB64)},\n    schema: ${JSON.stringify(schema)},\n    data: ${JSON.stringify(data)},\n  },`;
});

const out = `// DO NOT MODIFY — auto-generated by cli/scripts/gen-samples.cjs from the
// ${ids.join('/')} *.pdf, *.schema.json and *.data.json sample assets.
export interface SampleContent {
  pdfB64: string;
  schema: string;
  data: string;
}
export const SAMPLE_CONTENT: Record<string, SampleContent> = {
${entries.join('\n')}
};
`;

const target = path.join(dir, 'generated.ts');
fs.writeFileSync(target, out);
console.log(`gen-samples: wrote ${target} (${ids.length} samples)`);
